### ISSUE TITLE
Problem with prices/buying (balance)

### ISSUE THREAD

**Issue by 1337vexu** [SpyG-Studios/spyg-chestshop#1]
The problem is that when buying a thing, for example: diamond things with a price of $6000 and starts without $0 (Essentials Economy+Vault), it subtracts me from my account, allowing me to buy. And it should be the other way around, that it should require a given amount to be able to buy it, because it allows you to buy things indefinitely without having money
Minecraft version: 1.21
EssentialsX version: latest
Vault Version: Latest
SpygChestShop Version: Lastest

**Comment by ikoliHU** [comment]
We have fixed the issue, and now the system correctly requires the necessary amount before allowing purchases. Thank you for bringing this to our attention! We appreciate your reports and look forward to any future suggestions you may have for further improvements. 🚀

**Comment by quienn** [comment]
This still happens in 1.1.1 :( It puts the player's balance in negative 1, but the shop owner still gets paid

**Comment by ikoliHU** [comment]
Thats sould not be possible. Can you contact me on discord? @ikoli

**Comment by ikoliHU** [comment]
Thats sould not be possible. Can you contact me on discord? @ikoli
@quienn
